name: Coverage Comment

on:
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed

permissions:
  contents: read

jobs:
  comment:
    runs-on: ubuntu-latest
    name: Add Coverage PR Comment
    if: github.event.workflow_run.event == 'pull_request'
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Download coverage report
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ github.token }}
      - name: Download PR number
        uses: actions/download-artifact@v4
        with:
          name: pr-number
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ github.token }}
      - name: Read PR number
        id: pr
        run: echo "number=$(cat pr-number.txt)" >> "$GITHUB_OUTPUT"
      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@5770ad5eb8f42dd2c4f34da00c94c5381e49af88 # v3.0.5
        with:
          number: ${{ steps.pr.outputs.number }}
          recreate: true
          path: code-coverage-results.md
